
#define RDP_CONF_PATH		"/usr/ast/rdp.conf"
#define HOSTIP_PATH		    "/tmp/hostip"
#define UICONF_CONF_PATH	"/usr/ast/uiconf.conf"
#define SETTINGS_CONFIG_PATH "/usr/ast/setting.conf"
#define HOST_LIST_PATH	    "/usr/ast/hostlist"
#define VHOST_PATH	        "/tmp/vhost"

#define UI_CONF_PATH        "/usr/ast/ui.conf"
#define CRT_CONF_PATH       "/usr/ast/crt.conf"
#define UDHCPID_PATH        "/usr/ast/udhcpcid"

#define WAIT_CONF_PATH      "/usr/ast/wait.conf"
#define RDPID_PATH	        "/tmp/rdpid"
#define MANAGERID_PATH      "/usr/ast/mangerid"

#define DEFAULT_SETTINGS_CONFIG_PATH "/usr/ast/default_setting.conf"
#define SETTINGS_CONFIG_PATH "/usr/ast/setting.conf"
#define DEFAULT_ACCOUNT_CONFIG_PATH "/usr/ast/default_account.conf"
#define ACCOUNT_CONFIG_PATH "/usr/ast/account.conf"
#define DEFAULT_NET_CONFIG_PATH "/usr/ast/default_uiconf.conf"
#define NET_CONFIG_PATH "/usr/ast/uiconf.conf"
#define DEFAULT_USB_CONFIG_PATH "/usr/ast/default_usbfunction.conf"
#define USB_CONFIG_PATH "/usr/ast/usbfunction.conf"
#define DEFAULT_URBDRC_CONFIG_PATH "/usr/ast/default_urbdrc_function.conf"
#define URBDRC_CONFIG_PATH "/usr/ast/urbdrc_function.conf"
#define DEFAULT_SMARTCARD_CONFIG_PATH "/usr/ast/default_smartcard_function.conf"
#define SMARTCARD_CONFIG_PATH "/usr/ast/smartcard_function.conf"
#define DEFAULT_SYSTEM_CONFIG_PATH "/usr/ast/default_system.conf"
